```{r, include = FALSE}
library(tidyverse)
library(tidymodels)
library(cluster)
library(factoextra)
library(dendextend)
library(GGally)
```

```{r}
trucks=read_csv("trucks.csv")
```

```{r}
str(trucks)
summary(trucks)
```

```{r}
trucks = trucks %>% select(-Driver_ID)
str(trucks)
summary(trucks)
```

```{r}
ggplot(trucks, aes(x=Distance, y=Speeding)) + geom_point(alpha=0.5)
```


```{r}
kmeans_recipe = recipe(~ Distance + Speeding, trucks) 

trucks_dummy = kmeans_recipe %>% 
  step_dummy(all_nominal(), one_hot = TRUE) %>%
  step_scale(all_numeric()) %>%
  step_center(all_numeric()) 

trucks_dummy = prep(trucks_dummy, trucks) #prepares the recipe

trucks_cleaned = bake(trucks_dummy, trucks)
```

```{r}
summary(trucks)
summary(trucks_cleaned)
```

```{r}
set.seed(412)
clusts = 
  tibble(k = 1:8) %>%
  mutate(
    kclust = map(k, ~kmeans(trucks_cleaned, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, trucks_cleaned)
  )

clusts
```

```{r}
clusters = 
  clusts %>%
  unnest(cols = c(tidied))

assignments = 
  clusts %>% 
  unnest(cols = c(augmented))

clusterings = 
  clusts %>%
  unnest(cols = c(glanced))
```

```{r}
p1 = 
  ggplot(assignments, aes(x = Distance, y = Speeding)) +
  geom_point(aes(color = .cluster), alpha = 0.8) + 
  facet_wrap(~ k)
p1
```
```{r}
ggplot(clusterings, aes(k, tot.withinss)) +
  geom_line() +
  geom_point()
```

```{r}
set.seed(64)
clusters = kmeans(trucks_cleaned, 2)
```

```{r}
trucks = augment(clusters, trucks)
str(trucks)
```

```{r}
ggplot(trucks, aes(x=Distance,y=Speeding,color=factor(.cluster))) + geom_point()
```

```{r}
set.seed(64)
clusts1 = 
  tibble(k = 1:4) %>%
  mutate(
    kclust = map(k, ~kmeans(trucks_cleaned, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, trucks_cleaned)
  )

clusts1
```

```{r}
clusters = 
  clusts1 %>%
  unnest(cols = c(tidied))

assignments = 
  clusts1 %>% 
  unnest(cols = c(augmented))

clusterings = 
  clusts1 %>%
  unnest(cols = c(glanced))
```

```{r}
p1 = 
  ggplot(assignments, aes(x = Distance, y = Speeding)) +
  geom_point(aes(color = .cluster), alpha = 0.8) + 
  facet_wrap(~ k)
p1
```

